### ISSUE TITLE
Using a backgroundColor: white container

### ISSUE THREAD

**Issue by jamesholcomb** [buddy-bas/react-native-animated-wheel-picker#4]
When using a white background for the picker container, the selected value is not visible (white text on white background).

The example uses a pink background, so it doesn't present itself there.

**Comment by anwersolangi** [comment]
Hello @jamesholcomb I was also facing this same issue. I have changed [this](https://github.com/buddy-bas/react-native-animated-wheel-picker/blob/09221a638f7839bd57271e7bd54aaa6fcedd9bbc/src/components/Picker.tsx#L175) line of code and replaced **white** with `'rgba(52, 52, 52, 0.8)'`
I have created a Pull Request and replaced this code with a prop, which will help you to change the color dynamically and can help to add logic too.

**Comment by jamesholcomb** [comment]
I worked around it by passing in a custom `maskedComponents`

```jsx
const ITEM_HEIGHT = 40
const VISIBLE = 5

const maskedComponents = () => (
    <>
      <View
        style={{
          height: ITEM_HEIGHT * Math.trunc(VISIBLE / 2),
          backgroundColor: "gray"
        }}
      />
      <View
        style={{
          height: ITEM_HEIGHT,
          backgroundColor: theme.textColor
        }}
      />
      <View
        style={{
          height: ITEM_HEIGHT * Math.trunc(VISIBLE / 2),
          backgroundColor: "gray"
        }}
      />
    </>
  )
```

**Comment by anwersolangi** [comment]
> I worked around it by passing in a custom `maskedComponents`
> 
> ```js
> const ITEM_HEIGHT = 40
> const VISIBLE = 5
> 
> const maskedComponents = () => (
>     <>
>       <View
>         style={{
>           height: ITEM_HEIGHT * Math.trunc(VISIBLE / 2),
>           backgroundColor: "gray"
>         }}
>       />
>       <View
>         style={{
>           height: ITEM_HEIGHT,
>           backgroundColor: theme.textColor
>         }}
>       />
>       <View
>         style={{
>           height: ITEM_HEIGHT * Math.trunc(VISIBLE / 2),
>           backgroundColor: "gray"
>         }}
>       />
>     </>
>   )
> ```

Great, exactly what I did in the Pull Request... because most of the time dark and light theme matters, btw Thanks!
